server:
  port: 8000

eureka:
  client:
#    eureka-server-port: 8761
    register-with-eureka:  true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: gateway-api


spring:
#  main:
#    web-application-type: reactive
  application:
    name: gatewayservice
  cloud:
    gateway:
      globalcors:
       corsConfigurations:
          '[/**]':
            allowedOrigins: "http://127.0.0.1:5501/"
            allow-credentials: true   #추가
            allowedHeaders:
              - x-requested-with
              - Authorization
              - content-type
              - credential
              - X-AUTH-TOKEN
              - X-CSRF-TOKEN
            allowedMethods:
              - POST
              - GET
              - PUT
              - OPTIONS
              - DELETE
            exposedHeaders:
              - Authorization
              - RefreshToken 
      routes:
        - id: first-service
          uri: http://localhost:8080/login-api
          predicates:
            - Path=/login-api/**
        - id: second-service
          uri: http://localhost:8080/login
          predicates:
          - Path=/login/**
#          - Header= Authorization
#          filters:
#          - LoginFilter      
        - id: third-service
          uri: http://localhost:8081/study-api
          predicates:
          - Path=/study-api/**
#          filters:
#          - UserJwtAuthorizationFilter
#        - id: google-service
#          uri: http://localhost:8080/login/oauth2/code/google
#          predicates:
#          - Path=/loginapi/google/**          
#        - id: google-service2
#          uri: http://localhost:8081/test
#          predicates:
#          - Path=/google/test/**               
#        - id: sub-service
#          uri: http://localhost:8000/login
#          predicates:
#          - Path=/jwtsave/**
#          filters:
#          - JwtTokenSaveFilter         
#          filters:
#          - JwtAuthorizationFilter
          
#            
#          filters:
#          - AutorizationFilter
#        - id: second-service
#          uri: http://localhost:8082/
#          predicates:
#            - Path=/second-service/**
